sources:
  - ../../Pods/SourceryAdditions/SourceryAdditions/Classes/SourceryProtocols.swift
  - ../Models
templates:
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoCodable.stencil
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoEquatable.stencil
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoHashable.stencil
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoLenses.stencil
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoCases.stencil
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoInitializable.stencil
  - ../../../../SourceryAdditions/SourceryAdditions/Templates/AutoObjectDiff.stencil
  - Templates/AutoDatabaseMappable.stencil
output:
    Generated/